version: "3.9"

services:
  webserver:
    build:
      context: ./docker/apache/
      args:
        COMPOSER_VERSION: 2.1.14
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - training
    volumes:
      - ./:/var/www/training

volumes:
  db-data:

networks:
  training:
